
const MAD_LIB = getLongMadLib(); // You can try using both getShortMadLib() and getLongMadLib()

/**
 * This function is done for you.
 * This function is called when the page is initially loaded.
 * It will generate inputs based on the contents of the MAD_LIB.fillers list.
 * Each input has an associated label and error text that begins as empty.
 */
function setup() {
    let parentNode = document.getElementById("madlib-questions");

    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];

        let newDivNode = document.createElement("div");
        newDivNode.className = "mb-2"

        let newInputNode = document.createElement("input");
        newInputNode.id = currLib.id + "-input";
        newInputNode.style.maxWidth = "25em";
        newInputNode.className = "form-control"
        newInputNode.placeholder = currLib.exampleText;
        
        let newLabelNode = document.createElement("label");
        newLabelNode.htmlFor = currLib.id + "-input";
        newLabelNode.innerText = currLib.friendlyText;

        let newErrorTextNode = document.createElement("p");
        newErrorTextNode.id = currLib.id + "-error-text";
        newErrorTextNode.style.color = "red";
        newErrorTextNode.innerText = "";

        newDivNode.appendChild(newLabelNode);
        newDivNode.append(newInputNode);
        newDivNode.append(newErrorTextNode);

        parentNode.appendChild(newDivNode);
    }
}

/**
 * This function is done for you.
 * This function is called anytime the user presses the "Generate!" button.
 * It first checks if the given inputs are valid. If they are valid,
 * the madlib is generated by calling the generateLib function.
 */
function generate() {
    if (validate()) {
        generateLib();
        alert("Success! Please see below for your MadLib :)");
    } else {
        alert("Uh oh, please check your form submission.")
    }
}

console.log(MAD_LIB);
/**
 * This function is called by generate any time the user requests
 * generation and validation passes. Generate the `madlib-result` div
 * such that any existing HTML is replaced with the newest madlib contents.
 */
function generateLib() {
    const resultDiv = document.getElementById("madlib-result");
    resultDiv.innerHTML = "";

    let pBuilder = document.createElement("p"); 
    pBuilder.innerText = "";

    let currentParagraphString = "";
    for(entry of MAD_LIB.text ) {
        let output = document.createElement("p");
        switch(entry.segmentType) {
            case 'static':
                currentParagraphString += entry.text;
                // pBuilder.innerText += entry.text;
                break;
            case 'fillable':
                itemElement = document.querySelector("#"+entry.id+"-input");
                // pBuilder.innerText += itemElement.value;
                currentParagraphString += itemElement.value;
                break
            case 'newline':
                console.log(output);
                output.innerText = currentParagraphString;
                resultDiv.appendChild(output);
                currentParagraphString = "";
                break;
        }

    }



    console.log(MAD_LIB);


}

/**
 * This function should check if any of the inputs have validation errors.
 * For each input, if it has validation errors, set the appropriate error text.
 * Otherwise, reset any error text that may exist. Use error text appropriate to
 * each form control, for exdample if validation fails on a quote, the error text
 * should say 'Please type 1 or more characters between quotes.' If the validation fails 
 * on a word, the error text should say 'Please type 1 or more letters, without spaces.'
 * 
 * Be sure to return true or false! Return true if all inputs are valid,
 * otherwise return false if ANY input is invalid.
 * 
 * @returns {boolean} true if form is valid, false otherwise.
 */
function validate() {
    let isValid = true;
    
    // TODO: If any inputs are invalid, set their error text.
    //       After checking ALL inputs, return true/false if
    //       the entire form was valid or not.
    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];
        let currInputId = currLib.id + "-input";
        let currErrorTextId = currLib.id + "-error-text";
        // console.log(currLib, currInputId, currErrorTextId);
        
        let currValue = document.querySelector("#"+currInputId).value;
        // console.log(document.querySelector("#"+currInputId).value);
        switch(currLib.type) {
            case "word":
                console.log(currValue, " = Word: " + /^[A-Za-z]+$/.test(currValue) );
                if(!/^[A-Za-z]+$/.test(currValue)) {
                    document.querySelector("#"+currErrorTextId).innerHTML = "Please type 1 or more letters, without spaces or special characters."
                    return false;
                }
                else {
                        document.querySelector("#"+currErrorTextId).innerHTML = ""
                }
                break;
            case "adjective":
                console.log(currValue, " = Adjective: " + /^[A-Za-z]+[y]{1}$/.test(currValue) );
                if(!/^[A-Za-z]+[y]{1}$/.test(currValue)) {
                    document.querySelector("#"+currErrorTextId).innerHTML = "Please type 1 or more letters, without special characters, ending with a y."
                    return false;
                }
                else {
                    document.querySelector("#"+currErrorTextId).innerHTML = ""

                }
                break;
            case "quote":
                console.log(currValue, " = Quote: " + /(([']{1}.+[']{1})|(["]{1}.+["]{1}))/.test(currValue) );
                if(!/(([']{1}.+[']{1})|(["]{1}.+["]{1}))/.test(currValue)) {
                    document.querySelector("#"+currErrorTextId).innerHTML = "Please type 1 or more letters, without special characters, starting with a capital letter."
                    return false;
                }
                else {
                    document.querySelector("#"+currErrorTextId).innerHTML = ""
                }
                break;
            case "properNoun":
                // console.log("");
                console.log(currValue, " = Proper Noun: " + /^[A-Z]{1}[A-Za-z]+$/.test(currValue) );
                if(!/^[A-Z]{1}[A-Za-z]+$/.test(currValue)) {
                    document.querySelector("#"+currErrorTextId).innerHTML = "Please type 1 or more letters, without special characters, starting with a capital letter."
                    return false;
                }
                else {
                    document.querySelector("#"+currErrorTextId).innerHTML = ""
                }
                break;
            default:
                break;
        }
        
    }

    return isValid;
}

// Don't remove this! It runs the setup function on page load.
window.onload = setup;
